In [1]:
import pandas as pd

In [14]:
df = pd.read_csv('dash\csvs\AdIndex main news METRICS 2023-12-14.csv')
df.head()

,Unnamed: 0,date,author,post_tag,post_id,link,Посетители,Читатели,Уникальные пользователи,% недочитываемости,Глубина просмотра,Ср. время на сайте (сек),0
0,0,2023-12-13,Петрова Мария Сергеевна,Тенденции,318261,https://adindex.ru/news/tendencies/2023/12/13/...,5.0,30.0,5.0,0.0,2.00,16.500000,NaN
1,1,2023-12-13,Борисова Ольга Борисовна,Креатив,318259,https://adindex.ru/news/creative/2023/12/13/31...,14.0,71.0,14.0,0.0,3.50,79.214286,NaN
2,2,2023-12-13,Григорьева Людмила Григорьевна,Тенденции,318152,https://adindex.ru/news/tendencies/2023/12/13/...,17.0,46.0,17.0,25.0,1.25,14.750000,NaN
3,3,2023-12-13,Иванов Иван Иванович,Кадры,318116,https://adindex.ru/news/hr/2023/12/13/318116.p...,9.0,82.0,9.0,0.0,2.25,81.000000,NaN
4,4,2023-12-13,Егорова Надежда Андреевна,Социальные проекты,318115,https://adindex.ru/news/social_advertising/202...,5.0,8.0,5.0,50.0,1.00,11.000000,NaN

In [31]:
cl_df = df[['link','author','Читатели','Глубина просмотра']]

In [32]:
cl_df['трафик с ТГ']= 0
cl_df['трафик с ВК']= 0
cl_df['трафик с home']= 0

C:\Users\danie\AppData\Local\Temp\ipykernel_20432\2041541511.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cl_df['трафик с ТГ']= 0
C:\Users\danie\AppData\Local\Temp\ipykernel_20432\2041541511.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cl_df['трафик с ВК']= 0
C:\Users\danie\AppData\Local\Temp\ipykernel_20432\2041541511.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cl_df['трафик с home']= 0

In [33]:
cl_df

,link,author,Читатели,Глубина просмотра,трафик с ТГ,трафик с ВК,трафик с home
0,https://adindex.ru/news/tendencies/2023/12/13/...,Петрова Мария Сергеевна,30.0,2.00,0,0,0
1,https://adindex.ru/news/creative/2023/12/13/31...,Борисова Ольга Борисовна,71.0,3.50,0,0,0
2,https://adindex.ru/news/tendencies/2023/12/13/...,Григорьева Людмила Григорьевна,46.0,1.25,0,0,0
3,https://adindex.ru/news/hr/2023/12/13/318116.p...,Иванов Иван Иванович,82.0,2.25,0,0,0
4,https://adindex.ru/news/social_advertising/202...,Егорова Надежда Андреевна,8.0,1.00,0,0,0
...,...,...,...,...,...,...,...
94,https://adindex.ru/news/digital/2023/12/4/3176...,Борисова Ольга Борисовна,3.0,1.00,0,0,0
95,https://adindex.ru/news/marketing/2023/12/4/31...,Данилова Светлана Викторовна,2.0,1.00,0,0,0
96,https://adindex.ru/news/right/2023/12/4/317662...,Жукова Ирина Ильинична,4.0,4.00,0,0,0
97,https://adindex.ru/news/tendencies/2023/12/4/3...,Жукова Ирина Ильинична,3.0,3.00,0,0,0
98,https://adindex.ru/news/marketing/2023/12/4/31...,Андреева Анастасия Андреевна,3.0,1.00,0,0,0