In [6]:
import parser
import selenium.webdriver as webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import datetime

In [7]:
driver = webdriver.Chrome()

In [8]:
driver.get('https://adindex.ru/news/all.phtml')

In [9]:
mime_counter = 0

In [10]:
posts_cards = driver.find_elements(By.CLASS_NAME, 'newsfeed__list-item')
print('\n\n'.join([i.text for i in posts_cards]))

Сабо Crocs оказались в мире Бикини Боттом
Креатив 27.05.24 | 19:11

Первый пациент Neuralink рассказал про жизнь с чипом в мозге
Digital 27.05.24 | 19:07

Брендлокатор. Подрядчиков ищут: «ВКонтакте», Тele2, Газпромбанк
Эккаунты 27.05.24 | 18:33

Дэвид Бекхэм стал лицом AliExpress
Маркетинг 27.05.24 | 17:54

TJ Collection выпустил ИИ-стилиста
Digital 27.05.24 | 17:41

Сфера маркетинга и рекламы показала самую высокую конкуренцию среди кандидатов
Исследования 27.05.24 | 16:04

Бизнесмен Александр Соколовский снялся в мюзикле для банка «Точка»
Креатив 27.05.24 | 14:39

Функция проверки фактов может появиться в «Телеграме»
Digital 27.05.24 | 12:50

РАЭК посчитала рынок продвижения на маркетплейсах
Тенденции 27.05.24 | 11:54

YouTube Music добавил функцию поиска песни по напеву
Digital 27.05.24 | 10:06

Продажи театральных билетов в стране сократились на 9–25%
Тенденции 27.05.24 | 09:02

Продажи игровых приставок выросли на 70% в первом квартале
Тенденции 27.05.24 | 07:56

Россияне могли вложить в криптовалюту до $100 млрд
Тенденции 27.05.24 | 07:48

Рынок доставки продуктов и товаров вырос на 55% год к году
Тенденции 27.05.24 | 07:15

Более 50% опрошенных россиян сталкивались с возвратом товаров
Тенденции 27.05.24 | 07:08

«Сказочный патруль» появился во «Вкусно — и точка»
Маркетинг 24.05.24 | 18:46

In [16]:
for post_data in posts_cards:
    data = parser.get_post_data(post_data)
    print(data[0])
    print(data[1])
    
    print('\n\n')

                 date                   author  \
0 2024-05-27 19:11:00  Петрова Мария Сергеевна

                                   post_name post_tag post_id  \
0  Сабо Crocs оказались в мире Бикини Боттом  Креатив  322877

                                                link
0  https://adindex.ru/news/creative/2024/05/27/32...
2024-05-27 19:11:00



                 date                    author  \
0 2024-05-27 19:07:00  Борисова Ольга Борисовна

                                           post_name post_tag post_id  \
0  Первый пациент Neuralink рассказал про жизнь с...  Digital  322876

                                                link
0  https://adindex.ru/news/digital/2024/05/27/322...
2024-05-27 19:07:00



                 date                          author  \
0 2024-05-27 18:33:00  Григорьева Людмила Григорьевна

                                           post_name  post_tag post_id  \
0  Брендлокатор. Подрядчиков ищут: «ВКонтакте», Т...  Эккаунты  322874

                                                link
0  https://adindex.ru/news/ek/2024/05/27/322874.p...
2024-05-27 18:33:00



                 date                          author  \
0 2024-05-27 17:54:00  Григорьева Людмила Григорьевна

                            post_name   post_tag post_id  \
0  Дэвид Бекхэм стал лицом AliExpress  Маркетинг  322872

                                                link
0  https://adindex.ru/news/marketing/2024/05/27/3...
2024-05-27 17:54:00



                 date                author  \
0 2024-05-27 17:41:00  Иванов Иван Иванович

                            post_name post_tag post_id  \
0  TJ Collection выпустил ИИ-стилиста  Digital  322871

                                                link
0  https://adindex.ru/news/digital/2024/05/27/322...
2024-05-27 17:41:00



                 date                        author  \
0 2024-05-27 16:04:00  Данилова Светлана Викторовна

                                           post_name      post_tag post_id  \
0  Сфера маркетинга и рекламы показала самую высо...  Исследования  322868

                                                link
0  https://adindex.ru/news/researches/2024/05/27/...
2024-05-27 16:04:00



                 date                        author  \
0 2024-05-27 14:39:00  Данилова Светлана Викторовна

                                           post_name post_tag post_id  \
0  Бизнесмен Александр Соколовский снялся в мюзик...  Креатив  322864

                                                link
0  https://adindex.ru/news/creative/2024/05/27/32...
2024-05-27 14:39:00



                 date                          author  \
0 2024-05-27 12:50:00  Григорьева Людмила Григорьевна

                                           post_name post_tag post_id  \
0  Функция проверки фактов может появиться в «Тел...  Digital  322861

                                                link
0  https://adindex.ru/news/digital/2024/05/27/322...
2024-05-27 12:50:00



                 date                    author  \
0 2024-05-27 11:54:00  Борисова Ольга Борисовна

                                           post_name   post_tag post_id  \
0  РАЭК посчитала рынок продвижения на маркетплейсах  Тенденции  322859

                                                link
0  https://adindex.ru/news/tendencies/2024/05/27/...
2024-05-27 11:54:00



                 date                        author  \
0 2024-05-27 10:06:00  Андреева Анастасия Андреевна

                                           post_name post_tag post_id  \
0  YouTube Music добавил функцию поиска песни по ...  Digital  322857

                                                link
0  https://adindex.ru/news/digital/2024/05/27/322...
2024-05-27 10:06:00



                 date                   author  \
0 2024-05-27 09:02:00  Петрова Мария Сергеевна

                                           post_name   post_tag post_id  \
0  Продажи театральных билетов в стране сократили...  Тенденции  322858

                                                link
0  https://adindex.ru/news/tendencies/2024/05/27/...
2024-05-27 09:02:00



                 date                      author  \
0 2024-05-27 07:56:00  Сидоров Антон Владимирович

                                           post_name   post_tag post_id  \
0  Продажи игровых приставок выросли на 70% в пер...  Тенденции  322855

                                                link
0  https://adindex.ru/news/tendencies/2024/05/27/...
2024-05-27 07:56:00



                 date                author  \
0 2024-05-27 07:48:00  Иванов Иван Иванович

                                           post_name   post_tag post_id  \
0  Россияне могли вложить в криптовалюту до $100 ...  Тенденции  322856

                                                link
0  https://adindex.ru/news/tendencies/2024/05/27/...
2024-05-27 07:48:00



                 date                   author  \
0 2024-05-27 07:15:00  Петрова Мария Сергеевна

                                           post_name   post_tag post_id  \
0  Рынок доставки продуктов и товаров вырос на 55...  Тенденции  322854

                                                link
0  https://adindex.ru/news/tendencies/2024/05/27/...
2024-05-27 07:15:00



                 date                  author  \
0 2024-05-27 07:08:00  Жукова Ирина Ильинична

                                           post_name   post_tag post_id  \
0  Более 50% опрошенных россиян сталкивались с во...  Тенденции  322853

                                                link
0  https://adindex.ru/news/tendencies/2024/05/27/...
2024-05-27 07:08:00



                 date                          author  \
0 2024-05-24 18:46:00  Григорьева Людмила Григорьевна

                                           post_name   post_tag post_id  \
0  «Сказочный патруль» появился во «Вкусно — и то...  Маркетинг  322852

                                                link
0  https://adindex.ru/news/marketing/2024/05/24/3...
2024-05-24 18:46:00

In [15]:
next_button = driver.find_element(By.CLASS_NAME, 'mb-xl-0')
next_button.click()
mime_counter+=1

In [16]:
posts_cards = driver.find_elements(By.CLASS_NAME, 'newsfeed__list-item')[mime_counter*16:]
print('\n\n'.join([i.text for i in posts_cards]))
print(len(posts_cards))

«Тинькофф» выпустил тактильную карту для людей с нарушениями зрения
Социальные проекты 14:58 | 23.05.24

S7 Airlines попыталась поймать лето
Креатив 12:59 | 23.05.24

«Яндекс Маркет» создал свой бренд кофе
Маркетинг 12:09 | 23.05.24

Выручка VK от онлайн-рекламы выросла почти на четверть в первом квартале
Digital 10:40 | 23.05.24

Телеведущая Марина Кравец названа бренд-амбассадором Ozon
Маркетинг 10:16 | 23.05.24

Траты россиян на новые автомобили сократились на 13% в апреле
Тенденции 09:33 | 23.05.24

Раньше других начинают зарабатывать представители поколения Х
Тенденции 08:00 | 23.05.24

Российский бизнес заинтересовался Бахрейном
Тенденции 07:33 | 23.05.24

Стоимость размещения рекламных постов в «Телеграме» выросла на треть
Тенденции 07:15 | 23.05.24

Бренд «Два мяча» и «Яндекс Музей» создали вдохновленные нейросетями кеды
Креатив 18:41 | 22.05.24

Google активировал искусственный интеллект для рекламодателей
Digital 18:06 | 22.05.24

ФАС завела дело против МТС из-за роста стоимости услуг
Право 15:55 | 22.05.24

Лидеров рейтинга RQ Index среди российских банков назвали в Москве
Пресс-релизы 15:40 | 22.05.24

Quiet Media запустила первую на российском рынке CPA-платформу на базе сегментов телеком-операторов
Пресс-релизы 15:30 | 22.05.24

Дмитрий Лазарев возглавил сеть «585*Золотой»
Кадры 14:32 | 22.05.24

Четверть опрошенных россиян надеются на возвращение иностранных брендов мебели
Исследования 13:31 | 22.05.24
16

In [26]:
posts_cards = driver.find_elements(By.CLASS_NAME, 'newsfeed__list-item')
print('\n\n'.join([i.text for i in posts_cards][16 * mime_counter:]))

«Тинькофф» выпустил тактильную карту для людей с нарушениями зрения
Социальные проекты 14:58 | 23.05.24

S7 Airlines попыталась поймать лето
Креатив 12:59 | 23.05.24

«Яндекс Маркет» создал свой бренд кофе
Маркетинг 12:09 | 23.05.24

Выручка VK от онлайн-рекламы выросла почти на четверть в первом квартале
Digital 10:40 | 23.05.24

Телеведущая Марина Кравец названа бренд-амбассадором Ozon
Маркетинг 10:16 | 23.05.24

Траты россиян на новые автомобили сократились на 13% в апреле
Тенденции 09:33 | 23.05.24

Раньше других начинают зарабатывать представители поколения Х
Тенденции 08:00 | 23.05.24

Российский бизнес заинтересовался Бахрейном
Тенденции 07:33 | 23.05.24

Стоимость размещения рекламных постов в «Телеграме» выросла на треть
Тенденции 07:15 | 23.05.24

Бренд «Два мяча» и «Яндекс Музей» создали вдохновленные нейросетями кеды
Креатив 18:41 | 22.05.24

Google активировал искусственный интеллект для рекламодателей
Digital 18:06 | 22.05.24

ФАС завела дело против МТС из-за роста стоимости услуг
Право 15:55 | 22.05.24

Лидеров рейтинга RQ Index среди российских банков назвали в Москве
Пресс-релизы 15:40 | 22.05.24

Quiet Media запустила первую на российском рынке CPA-платформу на базе сегментов телеком-операторов
Пресс-релизы 15:30 | 22.05.24

Дмитрий Лазарев возглавил сеть «585*Золотой»
Кадры 14:32 | 22.05.24

Четверть опрошенных россиян надеются на возвращение иностранных брендов мебели
Исследования 13:31 | 22.05.24

In [ ]:
Посещаемость торгцентров

In [53]:
mime_counter = 5

In [56]:
[i.text for i in posts_cards[mime_counter*16: ]]

['В России создан аналог игры Diablo — «Первый богатырь»\nDigital 09:51 | 20.05.24',
 'Большинство российских геймеров скачивают видеоигры в обход оплаты\nТенденции 07:54 | 20.05.24',
 '«Яндекс» допустил увеличение роботов-курьеров в два раза\nТенденции 07:43 | 20.05.24',
 'Ввоз в страну импортной воды почти восстановился за два года\nТенденции 07:33 | 20.05.24',
 'Посещаемость торгцентров сократилась на 2–3% в мае год к году\nТенденции 06:58 | 20.05.24',
 'Экс-участница Serebro призвала носить украшения Unode50 «не в свет, а когда тебе этого хочется»\nКреатив 18:40 | 17.05.24',
 'Тимоти Шаламе показал свою «многогранность» для Chanel\nКреатив 17:11 | 17.05.24',
 'Часовые тиктоки, доходы от рекламы в подкастах и новая должность в GroupM — обзор новостей в зарубежных СМИ\nDigital 16:37 | 17.05.24',
 'Yandex N.V. завершила первый этап сделки по продаже «Яндекса»\nМаркетинг 15:24 | 17.05.24',
 '«ВкусВилл» создал «дачественную» доставку\nКреатив 14:29 | 17.05.24',
 'Треть опрошенных российских компаний отказались от зарубежных сервисов видеосвязи\nИсследования 12:38 | 17.05.24',
 '«Авито Услуги» помогли «без стресса» выбрать мастера для ремонта техники и строительства\nКреатив 11:57 | 17.05.24',
 'Шеф-повар Food.ru приготовил еду в имитирующих нарушение зрения VR-очках\nСоциальные проекты 10:42 | 17.05.24',
 'Группа «Тинькофф» увеличила расходы на маркетинг и рекламу почти в 1,7 раза\nМаркетинг 08:59 | 17.05.24',
 'ТЦ полностью заместили площади покинувших страну брендов\nТенденции 07:58 | 17.05.24',
 '«Литрес» начал искать неофициальных переводчиков для работы\nТенденции 07:39 | 17.05.24']

In [57]:
today = datetime.datetime.today().date()
date_to = today
date_from = datetime.date(today.year, today.month, 20)
parsed_datas = pd.DataFrame()

for post_data in posts_cards[mime_counter * 16:]:
    parsed_data, post_date = parser.get_post_data(post_data)
    post_date = datetime.date(post_date.year, post_date.month, post_date.day)

    print( date_from, date_to, post_date )
    
    if post_date <= date_to and post_date >= date_from:
        print('Добавили еще строчку')
        parsed_datas = pd.concat([parsed_datas, parsed_data], ignore_index = True)

    else:
        print('Время превышаем')
        continue_search = False
        break

2024-05-20 2024-05-28 2024-05-20
Добавили еще строчку
2024-05-20 2024-05-28 2024-05-20
Добавили еще строчку
2024-05-20 2024-05-28 2024-05-20
Добавили еще строчку
2024-05-20 2024-05-28 2024-05-20
Добавили еще строчку
2024-05-20 2024-05-28 2024-05-20
Добавили еще строчку
2024-05-20 2024-05-28 2024-05-17
Время превышаем

In [48]:
len(parsed_datas)

85

In [49]:
len(posts_cards)

96

In [58]:
parsed_datas

,date,author,post_name,post_tag,post_id,link
0,2024-05-20 09:51:00,Петрова Мария Сергеевна,В России создан аналог игры Diablo — «Первый б...,Digital,322695,https://adindex.ru/news/digital/2024/05/20/322...
1,2024-05-20 07:54:00,Сидоров Антон Владимирович,Большинство российских геймеров скачивают виде...,Тенденции,322694,https://adindex.ru/news/tendencies/2024/05/20/...
2,2024-05-20 07:43:00,Данилова Светлана Викторовна,«Яндекс» допустил увеличение роботов-курьеров ...,Тенденции,322693,https://adindex.ru/news/tendencies/2024/05/20/...
3,2024-05-20 07:33:00,Васильева Екатерина Васильевна,Ввоз в страну импортной воды почти восстановил...,Тенденции,322692,https://adindex.ru/news/tendencies/2024/05/20/...
4,2024-05-20 06:58:00,Жукова Ирина Ильинична,Посещаемость торгцентров сократилась на 2–3% в...,Тенденции,322691,https://adindex.ru/news/tendencies/2024/05/20/...

In [1]:
import parser
import selenium.webdriver as webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import datetime
import time

In [9]:
def parse_some_news(date_from : datetime.date, date_to : datetime.date, driver : webdriver.Chrome = None) -> pd.DataFrame:
    if not driver:
        driver = webdriver.Chrome()

    driver.get('https://adindex.ru/news/all.phtml')

    parsed_datas = pd.DataFrame()

    posts_cards = driver.find_elements(By.CLASS_NAME, 'newsfeed__list-item')
    continue_search = True
    checked_rounds = 0
    # date = datetime.date(1970, 1, 1)

    while continue_search:
        # print([i.text for i in posts_cards])
        # print(date_from, date_to, date, date <= date_to, date >= date_from, date <= date_to and date >= date_from)
        # print(checked_rounds, '\n\n')


        posts_cards = driver.find_elements(By.CLASS_NAME, 'newsfeed__list-item')
        # print([i.text for i in posts_cards])
        print(checked_rounds)

        for post_data in posts_cards[checked_rounds * 16 :]:
            parsed_data, post_date = parser.get_post_data(post_data)
            post_date = datetime.date(post_date.year, post_date.month, post_date.day)
            
            if post_date <= date_to and post_date >= date_from:
                parsed_datas = pd.concat([parsed_datas, parsed_data], ignore_index = True)

            else:
                continue_search = False
                break


        checked_rounds += 1


        next_button = driver.find_element(By.CLASS_NAME, 'mb-xl-0')
        next_button.click()

        time.sleep(1)

    driver.close()


    
    return(parsed_datas)

In [2]:
today = datetime.datetime.today().date()

In [3]:
result = parser.parse_some_news(datetime.date(today.year, today.month, 20), today)

0
1
2
3
4
5

In [5]:
result

,date,author,post_name,post_tag,post_id,link
0,2024-05-27 19:11:00,Григорьева Людмила Григорьевна,Сабо Crocs оказались в мире Бикини Боттом,Креатив,322877,https://adindex.ru/news/creative/2024/05/27/32...
1,2024-05-27 19:07:00,Егорова Надежда Андреевна,Первый пациент Neuralink рассказал про жизнь с...,Digital,322876,https://adindex.ru/news/digital/2024/05/27/322...
2,2024-05-27 18:33:00,Сидоров Антон Владимирович,"Брендлокатор. Подрядчиков ищут: «ВКонтакте», Т...",Эккаунты,322874,https://adindex.ru/news/ek/2024/05/27/322874.p...
3,2024-05-27 17:54:00,Сидоров Антон Владимирович,Дэвид Бекхэм стал лицом AliExpress,Маркетинг,322872,https://adindex.ru/news/marketing/2024/05/27/3...
4,2024-05-27 17:41:00,Жукова Ирина Ильинична,TJ Collection выпустил ИИ-стилиста,Digital,322871,https://adindex.ru/news/digital/2024/05/27/322...
...,...,...,...,...,...,...
80,2024-05-20 09:51:00,Сидоров Антон Владимирович,В России создан аналог игры Diablo — «Первый б...,Digital,322695,https://adindex.ru/news/digital/2024/05/20/322...
81,2024-05-20 07:54:00,Иванов Иван Иванович,Большинство российских геймеров скачивают виде...,Тенденции,322694,https://adindex.ru/news/tendencies/2024/05/20/...
82,2024-05-20 07:43:00,Григорьева Людмила Григорьевна,«Яндекс» допустил увеличение роботов-курьеров ...,Тенденции,322693,https://adindex.ru/news/tendencies/2024/05/20/...
83,2024-05-20 07:33:00,Данилова Светлана Викторовна,Ввоз в страну импортной воды почти восстановил...,Тенденции,322692,https://adindex.ru/news/tendencies/2024/05/20/...
84,2024-05-20 06:58:00,Сидоров Антон Владимирович,Посещаемость торгцентров сократилась на 2–3% в...,Тенденции,322691,https://adindex.ru/news/tendencies/2024/05/20/...

In [7]:
url = result.iloc[0].link

In [20]:
def get_data_from_url(url: str, days_from : str = "yesterday", days_to : str = "today"):
    from statistics import median
    import requests


    params = {
        'ids': '22386646',
        # 'metrics': 'ym:s:visits,ym:s:pageviews,ym:s:users,ym:s:bounceRate,ym:s:pageDepth,ym:s:avgVisitDurationSeconds',
        # 'metrics': 'ym:s:pageviews',  # Метрика для просмотров страниц
        'metrics': 'ym:s:visits,ym:s:pageviews,ym:s:users,ym:s:bounceRate,ym:s:pageDepth,ym:s:avgVisitDurationSeconds',
        'dimensions': 'ym:s:refererDomain',  # Размерность для получения ссылок
        'date1': days_from,  # 7daysAgo за неделю, 30daysAgo за месяц, 365daysAgo за год
        'date2': days_to,
        'filters': f"ym:pv:URL=='{url}'"
    }

    api_url = 'https://api-metrika.yandex.net/stat/v1/data'


    headers = {
        # 'Authorization': 'OAuth y0_AgAAAABxT5u9AArjtwAAAADzHTIKv-VGe5uzTHqKqd3WWTTeIiZQ2WU',
        'Authorization': 'OAuth y0_AgAAAABxT5u9AArjtwAAAAEF76JkAACyj6gBOhNAkqhvgQqQ8cXYqh1BlA',
    }

    response = requests.get(api_url, headers=headers, params=params ).json()

    print(response)

    if not response['data']:
        return response, url


    page_metrics = []
    response_data = response['data']
    names = ['Посетители', "Читатели", "Уникальные пользователи", "% недочитываемости", "Глубина просмотра", "Ср. время на сайте (сек)"]


    for data in response_data:
        page_metrics.append(
            {
                'Сайт' : data['dimensions'][0]['name']
            }
        )

        for counter, metric_name in enumerate(names):
            page_metrics[-1].update(
                {
                    metric_name : data['metrics'][counter]
                }
            )
    out = [{}, {}, {'% недочитываемости' : [], 'Глубина просмотра' : [], "Ср. время на сайте (сек)"  : []}]

    restrict_keys = ['Сайт', '% недочитываемости', 'Глубина просмотра', "Ср. время на сайте (сек)"]


    for data in page_metrics:
        if 'telegram' not in data['Сайт']:
            if out[0]:
                out[0].update(
                    {
                        key : out[0][key] + data[key] for key in list(data.keys())[ : -3][1 :]
                    } 
                )
            
            else:
                for key in data:
                    if key != 'Сайт':
                        out[0][key] = data[key]


            for key in restrict_keys[1 :]:
                out[2][key].append(data[key])

        else:
            for key in data:
                if key != 'Сайт':
                    out[1][key] = round(data[key], 2)

    for key in out[2]:
        out[0][key] = median(out[2][key])

    del out[2]


    out[0] = {
        'Поисковые системы' : out[0]
    }

    out[1] = {
        'Telegram' : out[1]
    }

    totals = {}

    print(out, '\n')

    if out[1]['Telegram']:
        totals.update(
            {
                key : out[0]['Поисковые системы'][key] + out[1]['Telegram'][key]
                for key in list(out[0]['Поисковые системы'].keys())[ : 3]
            }
        )

        totals.update(
            {
                key : median([out[0]['Поисковые системы'][key], out[1]['Telegram'][key]])
                for key in list(out[0]['Поисковые системы'].keys())[3 :]
            }
        )

    else:
        totals.update(
            out[0]['Поисковые системы']
        )

    totals.update({'link' : url})
    # return response.json()
    return out, totals

In [22]:
get_data_from_url(url, '2daysAgo', 'today')

{'errors': [{'error_type': 'access_denied', 'message': 'Access is denied'}], 'code': 403, 'message': 'Access is denied'}

KeyError: 'data'

In [8]:
datetime.date(today.year, today.month, 20) - today

datetime.timedelta(days=-8)