In [15]:
import pandas as pd
import plotly.express as px

In [16]:
df = pd.read_csv('csvs\AdIndex main news METRICS 2023-12-14.csv', index_col=0, parse_dates=True)

C:\Users\danie\AppData\Local\Temp\ipykernel_34976\748554966.py:1: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

In [17]:
df

,date,Автор,post_tag,post_id,Ссылка,Посетители,Читатели,Уникальные пользователи,% недочитываемости,Глубина просмотра,Ср. время на сайте (сек),0
0,2023-12-13,Петрова Мария Сергеевна,Тенденции,318261,https://adindex.ru/news/tendencies/2023/12/13/...,5.0,30.0,5.0,0.000000,2.00,16.500000,NaN
1,2023-12-13,Борисова Ольга Борисовна,Креатив,318259,https://adindex.ru/news/creative/2023/12/13/31...,14.0,71.0,14.0,0.000000,3.50,79.214286,NaN
2,2023-12-13,Григорьева Людмила Григорьевна,Тенденции,318152,https://adindex.ru/news/tendencies/2023/12/13/...,17.0,46.0,17.0,25.000000,1.25,14.750000,NaN
3,2023-12-13,Иванов Иван Иванович,Кадры,318116,https://adindex.ru/news/hr/2023/12/13/318116.p...,9.0,82.0,9.0,0.000000,2.25,81.000000,NaN
4,2023-12-13,Егорова Надежда Андреевна,Социальные проекты,318115,https://adindex.ru/news/social_advertising/202...,5.0,8.0,5.0,50.000000,1.00,11.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
94,2023-12-04,Борисова Ольга Борисовна,Digital,317666,https://adindex.ru/news/digital/2023/12/4/3176...,3.0,3.0,3.0,25.000000,1.00,11.250000,NaN
95,2023-12-04,Данилова Светлана Викторовна,Маркетинг,317663,https://adindex.ru/news/marketing/2023/12/4/31...,2.0,2.0,2.0,50.000000,1.00,8.000000,NaN
96,2023-12-04,Жукова Ирина Ильинична,Право,317662,https://adindex.ru/news/right/2023/12/4/317662...,1.0,4.0,1.0,0.000000,4.00,8.000000,NaN
97,2023-12-04,Жукова Ирина Ильинична,Тенденции,317657,https://adindex.ru/news/tendencies/2023/12/4/3...,1.0,3.0,1.0,0.000000,3.00,1149.000000,NaN
98,2023-12-04,Андреева Анастасия Андреевна,Маркетинг,317656,https://adindex.ru/news/marketing/2023/12/4/31...,3.0,3.0,3.0,33.333333,1.00,10.333333,NaN

In [18]:
df['date'] = df['date'].apply(lambda x: pd.to_datetime(x))

In [19]:
df

,date,Автор,post_tag,post_id,Ссылка,Посетители,Читатели,Уникальные пользователи,% недочитываемости,Глубина просмотра,Ср. время на сайте (сек),0
0,2023-12-13,Петрова Мария Сергеевна,Тенденции,318261,https://adindex.ru/news/tendencies/2023/12/13/...,5.0,30.0,5.0,0.000000,2.00,16.500000,NaN
1,2023-12-13,Борисова Ольга Борисовна,Креатив,318259,https://adindex.ru/news/creative/2023/12/13/31...,14.0,71.0,14.0,0.000000,3.50,79.214286,NaN
2,2023-12-13,Григорьева Людмила Григорьевна,Тенденции,318152,https://adindex.ru/news/tendencies/2023/12/13/...,17.0,46.0,17.0,25.000000,1.25,14.750000,NaN
3,2023-12-13,Иванов Иван Иванович,Кадры,318116,https://adindex.ru/news/hr/2023/12/13/318116.p...,9.0,82.0,9.0,0.000000,2.25,81.000000,NaN
4,2023-12-13,Егорова Надежда Андреевна,Социальные проекты,318115,https://adindex.ru/news/social_advertising/202...,5.0,8.0,5.0,50.000000,1.00,11.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
94,2023-12-04,Борисова Ольга Борисовна,Digital,317666,https://adindex.ru/news/digital/2023/12/4/3176...,3.0,3.0,3.0,25.000000,1.00,11.250000,NaN
95,2023-12-04,Данилова Светлана Викторовна,Маркетинг,317663,https://adindex.ru/news/marketing/2023/12/4/31...,2.0,2.0,2.0,50.000000,1.00,8.000000,NaN
96,2023-12-04,Жукова Ирина Ильинична,Право,317662,https://adindex.ru/news/right/2023/12/4/317662...,1.0,4.0,1.0,0.000000,4.00,8.000000,NaN
97,2023-12-04,Жукова Ирина Ильинична,Тенденции,317657,https://adindex.ru/news/tendencies/2023/12/4/3...,1.0,3.0,1.0,0.000000,3.00,1149.000000,NaN
98,2023-12-04,Андреева Анастасия Андреевна,Маркетинг,317656,https://adindex.ru/news/marketing/2023/12/4/31...,3.0,3.0,3.0,33.333333,1.00,10.333333,NaN

In [20]:
df_filtered = df[df['Автор'] == 'Петрова Мария Сергеевна']
df_filtered

,date,Автор,post_tag,post_id,Ссылка,Посетители,Читатели,Уникальные пользователи,% недочитываемости,Глубина просмотра,Ср. время на сайте (сек),0
0,2023-12-13,Петрова Мария Сергеевна,Тенденции,318261,https://adindex.ru/news/tendencies/2023/12/13/...,5.0,30.0,5.0,0.000000,2.000000,16.50,NaN
9,2023-12-13,Петрова Мария Сергеевна,Тенденции,318089,https://adindex.ru/news/tendencies/2023/12/13/...,12.0,127.0,12.0,0.000000,1.000000,19.00,NaN
10,2023-12-13,Петрова Мария Сергеевна,Маркетинг,318088,https://adindex.ru/news/marketing/2023/12/13/3...,35.0,125.0,35.0,20.000000,1.705882,16.80,NaN
16,2023-12-12,Петрова Мария Сергеевна,Креатив,318080,https://adindex.ru/news/creative/2023/12/12/31...,31.0,104.0,31.0,0.000000,1.464286,45.75,NaN
27,2023-12-12,Петрова Мария Сергеевна,Право,317964,https://adindex.ru/news/right/2023/12/12/31796...,7.0,73.0,7.0,29.166667,10.583333,841.00,NaN
28,2023-12-12,Петрова Мария Сергеевна,Тенденции,317963,https://adindex.ru/news/tendencies/2023/12/12/...,5.0,5.0,5.0,0.000000,1.000000,15.00,NaN
52,2023-12-08,Петрова Мария Сергеевна,Право,317818,https://adindex.ru/news/right/2023/12/8/317818...,8.0,15.0,8.0,0.000000,1.250000,19.75,NaN
69,2023-12-06,Петрова Мария Сергеевна,Исследования,317721,https://adindex.ru/news/researches/2023/12/6/3...,2.0,6.0,2.0,50.000000,3.000000,109.00,NaN
74,2023-12-06,Петрова Мария Сергеевна,Право,317711,https://adindex.ru/news/right/2023/12/6/317711...,1.0,10.0,1.0,0.000000,10.000000,2291.00,NaN
80,2023-12-05,Петрова Мария Сергеевна,Маркетинг,317699,https://adindex.ru/news/marketing/2023/12/5/31...,2.0,2.0,1.0,50.000000,1.000000,12.00,NaN
89,2023-12-04,Петрова Мария Сергеевна,Тенденции,317681,https://adindex.ru/news/tendencies/2023/12/4/3...,1.0,10.0,1.0,0.000000,10.000000,2291.00,NaN

In [21]:
best_topic_tag_for_author = px.bar(df_filtered, x='post_tag', y='Читатели', title='Читатели Петровой Марии Сергеевны', 
             labels={'post_tag':'Тег поста'}, width=1000, height=600, hover_data={'post_id': True, 'Читатели': True}) 

best_topic_tag_for_author.show()

In [22]:
grouped_author = df.groupby('Автор').agg(
    total_readers=pd.NamedAgg(column='Читатели', aggfunc='sum'),
    total_posts=pd.NamedAgg(column='post_tag', aggfunc='count'),
    avg_depth=pd.NamedAgg(column='Глубина просмотра', aggfunc='mean'),
    best_topic=pd.NamedAgg(column='post_tag', aggfunc=lambda x: df.loc[x.index, 'Читатели'].idxmax())).reset_index()

grouped_author['best_topic'] = grouped_author['best_topic'].apply(lambda x: df.loc[x, 'post_tag'])

grouped_author.columns = ['Автор', 'Количество просмотров', 'Количество статей', 'Глубина', 'Лучшая тема (По просмотрам)']

print(grouped_author)

                            Автор  Количество просмотров  Количество статей  \
0    Андреева Анастасия Андреевна                  236.0                  6
1        Борисова Ольга Борисовна                  635.0                 13
2  Васильева Екатерина Васильевна                  840.0                 10
3  Григорьева Людмила Григорьевна                  541.0                  8
4    Данилова Светлана Викторовна                  126.0                 11
5       Егорова Надежда Андреевна                  299.0                  8
6          Жукова Ирина Ильинична                  681.0                 16
7            Иванов Иван Иванович                  400.0                 11
8         Петрова Мария Сергеевна                  507.0                 11
9      Сидоров Антон Владимирович                 1220.0                  5

     Глубина Лучшая тема (По просмотрам)
0   2.846774                       Медиа
1   2.382173                       Медиа
2   5.239103                   Маркетинг
3   1.276730                       Медиа
4   3.742424                   Тенденции
5   5.212054                Исследования
6   5.424479                       Право
7   3.302273                   Маркетинг
8   3.909409                   Тенденции
9  10.400000                   Маркетинг

In [23]:
sum_read = df.groupby('Автор')['Читатели'].sum().reset_index()
sum_read.sort_values(by='Читатели', ascending=False, inplace=True)

In [24]:
best_topic_author = px.bar(sum_read, x='Автор', y='Читатели', title='Топ ебанных пеиков', 
            width=1400, height=800)


best_topic_author.show()

In [25]:
grouped_teg = df.groupby('post_tag').agg(
    total_readers=pd.NamedAgg(column='Читатели', aggfunc='sum'),
    total_posts=pd.NamedAgg(column='post_tag', aggfunc='count'),
    best_author=pd.NamedAgg(column='Глубина просмотра', aggfunc='mean'))
grouped_teg

                    total_readers  total_posts  best_author
post_tag
AdYummy!                     36.0            2    15.000000
Digital                     331.0           10     4.773810
Агентства                    96.0            2     1.525000
Дизайн                       31.0            1     1.000000
Исследования                286.0            6     3.560185
Кадры                       125.0            3     2.702381
Креатив                     630.0            7     3.831711
Маркетинг                  1761.0           16     2.825368
Медиа                       667.0            5     1.227468
Право                       588.0           18     3.707407
Пресс-релизы                 19.0            2     1.000000
Рекламные бюджеты            83.0            2    10.416667
Социальные проекты           78.0            4     1.589286
Тенденции                   740.0           18     6.766204
Эккаунты                     14.0            3     1.500000

In [26]:
df

,date,Автор,post_tag,post_id,Ссылка,Посетители,Читатели,Уникальные пользователи,% недочитываемости,Глубина просмотра,Ср. время на сайте (сек),0
0,2023-12-13,Петрова Мария Сергеевна,Тенденции,318261,https://adindex.ru/news/tendencies/2023/12/13/...,5.0,30.0,5.0,0.000000,2.00,16.500000,NaN
1,2023-12-13,Борисова Ольга Борисовна,Креатив,318259,https://adindex.ru/news/creative/2023/12/13/31...,14.0,71.0,14.0,0.000000,3.50,79.214286,NaN
2,2023-12-13,Григорьева Людмила Григорьевна,Тенденции,318152,https://adindex.ru/news/tendencies/2023/12/13/...,17.0,46.0,17.0,25.000000,1.25,14.750000,NaN
3,2023-12-13,Иванов Иван Иванович,Кадры,318116,https://adindex.ru/news/hr/2023/12/13/318116.p...,9.0,82.0,9.0,0.000000,2.25,81.000000,NaN
4,2023-12-13,Егорова Надежда Андреевна,Социальные проекты,318115,https://adindex.ru/news/social_advertising/202...,5.0,8.0,5.0,50.000000,1.00,11.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
94,2023-12-04,Борисова Ольга Борисовна,Digital,317666,https://adindex.ru/news/digital/2023/12/4/3176...,3.0,3.0,3.0,25.000000,1.00,11.250000,NaN
95,2023-12-04,Данилова Светлана Викторовна,Маркетинг,317663,https://adindex.ru/news/marketing/2023/12/4/31...,2.0,2.0,2.0,50.000000,1.00,8.000000,NaN
96,2023-12-04,Жукова Ирина Ильинична,Право,317662,https://adindex.ru/news/right/2023/12/4/317662...,1.0,4.0,1.0,0.000000,4.00,8.000000,NaN
97,2023-12-04,Жукова Ирина Ильинична,Тенденции,317657,https://adindex.ru/news/tendencies/2023/12/4/3...,1.0,3.0,1.0,0.000000,3.00,1149.000000,NaN
98,2023-12-04,Андреева Анастасия Андреевна,Маркетинг,317656,https://adindex.ru/news/marketing/2023/12/4/31...,3.0,3.0,3.0,33.333333,1.00,10.333333,NaN

In [27]:
# Группировка данных по автору и теме, а затем рассчет среднего количества просмотров
grouped_data = pd.DataFrame(df.groupby(['Автор', 'post_tag'])['Читатели'].mean())

# Переименование столбца среднего количества просмотров для ясности
grouped_data.rename(columns={'Читатели': 'Среднее количество просмотров'}, inplace=True)

# Вывод первых нескольких строк таблицы
grouped_data

                                        Среднее количество просмотров
Автор                        post_tag
Андреева Анастасия Андреевна Digital                             46.0
                             Креатив                             45.0
                             Маркетинг                           31.5
                             Медиа                               73.0
                             Право                                9.0
...                                                               ...
Петрова Мария Сергеевна      Тенденции                           43.0
Сидоров Антон Владимирович   Креатив                             89.0
                             Маркетинг                         1089.0
                             Право                                8.5
                             Тенденции                           25.0

[66 rows x 1 columns]

In [ ]:
average_views_per_author = df.groupby('author')['Читатели'].mean()
top_10_authors = average_views_per_author.sort_values(ascending=False).head(10)

print(top_10_authors)

In [ ]:
# Отсортируйте таблицу с средними просмотрами по убыванию
sorted_data = grouped_data.sort_values(by='Среднее количество просмотров', ascending=False)

# Выберите топ-10 авторов
top_10_authors = sorted_data.index.get_level_values(0).unique()[:10]

# Создаем список для хранения данных
data_list = []

# Для каждого автора из топ-10 выбираем темы, в которых он был наиболее популярен
for author in top_10_authors:
    author_data = sorted_data.loc[author]
    top_topic = author_data.idxmax()[0]  # Находим тему с максимальным средним количеством просмотров
    top_views = author_data.max()  # Получаем максимальное среднее количество просмотров
    
    # Получаем общее количество статей по этой теме для данного автора
    total_articles = df[(df['author'] == author) & (df['post_tag'] == top_topic)].shape[0]
    
    # Получаем общее количество просмотров статей данного authorа по этой теме
    total_views = df[(df['author'] == author) & (df['post_tag'] == top_topic)]['Читатели'].sum()
    
    # Добавляем данные в список
    data_list.append({'author': author, 
                      'post_tag': top_topic, 
                      'Среднее количество просмотров': top_views[0],
                      'Общее количество статей по теме': total_articles,
                      'Общее количество просмотров статей': total_views})

# Создаем DataFrame из списка
top_authors_by_topic = pd.DataFrame(data_list)

# Выводим результаты
top_authors_by_topic

In [ ]:
df[(df['author'] == 'Сидоров Антон Владимирович') & (df['post_tag'] == 'Маркетинг')]

,date,author,post_tag,post_id,link,Посетители,Читатели,Уникальные пользователи,% недочитываемости,Глубина просмотра,Ср. время на сайте (сек),0
26,2023-12-12,Сидоров Антон Владимирович,Маркетинг,317968,https://adindex.ru/news/marketing/2023/12/12/3...,937.0,1089.0,882.0,0.0,1.0,15.0,NaN

In [ ]:
# Группируем данные по автору и теме, а затем подсчитываем количество уникальных публикаций
publications_per_author_topic = pd.DataFrame(df.groupby(['author', 'post_tag'])['post_id'].nunique())

# Переименовываем столбец с количеством публикаций для ясности
publications_per_author_topic.rename(columns={'post_id': 'Количество публикаций'}, inplace=True)

# Выводим результаты
# publications_per_author_topic
publications_per_author_topic.loc['Андреева Анастасия Андреевна'].reset_index()

    post_tag  Количество публикаций
0    Digital                      1
1    Креатив                      1
2  Маркетинг                      2
3      Медиа                      1
4      Право                      1

In [ ]:
# Группируем данные по автору и подсчитываем количество уникальных публикаций
total_publications_per_author = df.groupby(['author', 'post_tag'])['post_id'].nunique().reset_index()

# Переименовываем столбец с количеством публикаций для ясности
total_publications_per_author.rename(columns={'post_id': 'Общее количество публикаций'}, inplace=True)

# Выводим результаты
total_publications_per_author

                          author   post_tag  Общее количество публикаций
0   Андреева Анастасия Андреевна    Digital                            1
1   Андреева Анастасия Андреевна    Креатив                            1
2   Андреева Анастасия Андреевна  Маркетинг                            2
3   Андреева Анастасия Андреевна      Медиа                            1
4   Андреева Анастасия Андреевна      Право                            1
..                           ...        ...                          ...
61       Петрова Мария Сергеевна  Тенденции                            4
62    Сидоров Антон Владимирович    Креатив                            1
63    Сидоров Антон Владимирович  Маркетинг                            1
64    Сидоров Антон Владимирович      Право                            2
65    Сидоров Антон Владимирович  Тенденции                            1

[66 rows x 3 columns]